version: '3.8'

services:
    db:
        hostname: sistema-apice
        image: mariadb:lts
        restart: always
        environment:
            - MARIADB_DATABASE=sistemaApice
            - MARIADB_USER=root
            - MARIADB_ROOT_PASSWORD=mariadb
        ports:
            - 3306:3306
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - backend
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "--silent"]
            timeout: 1s
            retries: 5

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    pi-web:
        build: ./PI_WEB
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
                restart: true
        networks:
            - backend

volumes:
    mariadb_data:

networks:
    backend: {}
