# Generated by Django 4.2.2 on 2023-06-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRetirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('data', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ra', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('emprestimos', models.ManyToManyField(through='PI_WEB.Emprestimo', to='PI_WEB.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI_WEB.usuario')),
                ('curso', models.CharField(max_length=7)),
            ],
            bases=('PI_WEB.usuario',),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.reserva'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='responsavel_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.usuario'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_feitos', to='PI_WEB.usuario'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI_WEB.usuario')),
                ('funcao', models.CharField(max_length=9)),
                ('ferramentas_reservadas', models.ManyToManyField(through='PI_WEB.Reserva', to='PI_WEB.ferramenta')),
            ],
            bases=('PI_WEB.usuario',),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.servidor'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='supervisor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_supervisionados', to='PI_WEB.servidor'),
        ),
    ]
