# Generated by Django 4.2.6 on 2023-10-24 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRetirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Perigoso', 'Perigoso'), ('Seguro', 'Seguro')], max_length=10)),
                ('imagem', models.ImageField(default='default.png', upload_to='ferramentas')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ra', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('emprestimos', models.ManyToManyField(blank=True, through='PI_WEB.Emprestimo', to='PI_WEB.reserva')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI_WEB.usuario')),
                ('curso', models.CharField(max_length=7)),
            ],
            bases=('PI_WEB.usuario',),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.reserva'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='responsavel_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.usuario'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_feitos', to='PI_WEB.usuario'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PI_WEB.usuario')),
                ('funcao', models.CharField(choices=[('P', 'Professor'), ('B', 'Bolsista')], max_length=1)),
                ('ferramentas_reservadas', models.ManyToManyField(blank=True, through='PI_WEB.Reserva', to='PI_WEB.ferramenta')),
            ],
            bases=('PI_WEB.usuario',),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PI_WEB.servidor'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='supervisor_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_supervisionados', to='PI_WEB.servidor'),
        ),
    ]
