# Generated by Django 4.2.2 on 2023-07-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PI_WEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='imagem',
            field=models.ImageField(default='default.png', upload_to='imagens_ferramentas'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='password',
            field=models.CharField(default='123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ferramentas_reservadas',
            field=models.ManyToManyField(blank=True, through='PI_WEB.Reserva', to='PI_WEB.ferramenta'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='funcao',
            field=models.CharField(choices=[('P', 'Profesosr'), ('B', 'Bolsista')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emprestimos',
            field=models.ManyToManyField(blank=True, through='PI_WEB.Emprestimo', to='PI_WEB.reserva'),
        ),
    ]
