# Generated by Django 4.1.7 on 2023-10-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PI_WEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='imagem',
            field=models.ImageField(default='default.png', height_field=128, upload_to='PI_WEB/media/ferramentas', width_field=128),
        ),
    ]
