# Generated by Django 4.1.7 on 2023-09-19 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PI_WEB', '0002_ferramenta_imagem_servidor_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='password',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
