# Generated by Django 4.2.6 on 2023-10-19 13:56

from django.db import migrations
    
class Migration(migrations.Migration):

    dependencies = [
        ('PI_WEB', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        
    ]

    operations = [
        
        ]
