# Generated by Django 4.2.2 on 2023-07-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PI_WEB', '0003_alter_servidor_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='ferramentas_reservadas',
            field=models.ManyToManyField(blank=True, null=True, through='PI_WEB.Reserva', to='PI_WEB.ferramenta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emprestimos',
            field=models.ManyToManyField(blank=True, null=True, through='PI_WEB.Emprestimo', to='PI_WEB.reserva'),
        ),
    ]
