# Generated by Django 4.2.6 on 2023-10-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PI_WEB', '0003_alter_ferramenta_imagem_alter_ferramenta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='imagem',
            field=models.ImageField(default='default.png', upload_to='ferramentas'),
        ),
    ]
