# Generated by Django 4.2.6 on 2023-10-19 13:56

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Group
from PI_WEB.models import *


def create_groups_permissions(apps, schema):
    bolsistas, created = Group.objects.get_or_create(name='Bolsistas')
    professores, created = Group.objects.get_or_create(name='Professores')

    aluno = ContentType.objects.get_for_model(Aluno)
    emprestimo = ContentType.objects.get_for_model(Emprestimo)
    reserva = ContentType.objects.get_for_model(Reserva)
    ferramenta = ContentType.objects.get_for_model(Ferramenta)

    # aluno = "aluno"
    # emprestimo = "emprestimo"
    # reserva = "reserva"
    # ferramenta = "ferramenta"
    bolsistas.permissions.add(*Permission.objects.filter(content_type=aluno))
    bolsistas.permissions.add(*Permission.objects.filter(content_type=emprestimo))
    bolsistas.permissions.add(*Permission.objects.filter(content_type=reserva))
    bolsistas.permissions.add(*Permission.objects.filter(content_type=ferramenta))


    professores.permissions.add(*Permission.objects.filter(content_type=reserva))
    professores.permissions.add(Permission.objects.get(codename="view_ferramenta", content_type=ferramenta))
    professores.permissions.add(Permission.objects.get(codename="view_emprestimo", content_type=emprestimo))
    professores.permissions.add(Permission.objects.get(codename="view_aluno", content_type=aluno))

    print(bolsistas.permissions.all())
    print(professores.permissions.all())
    
class Migration(migrations.Migration):

    dependencies = [
        ('PI_WEB', '0001_initial'),
        
    ]

    operations = [
        migrations.RunPython(create_groups_permissions)
    ]
