# Generated by Django 4.2.2 on 2023-07-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PI_WEB', '0004_alter_servidor_ferramentas_reservadas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='servidor',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ferramentas_reservadas',
            field=models.ManyToManyField(blank=True, through='PI_WEB.Reserva', to='PI_WEB.ferramenta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emprestimos',
            field=models.ManyToManyField(blank=True, through='PI_WEB.Emprestimo', to='PI_WEB.reserva'),
        ),
    ]
