# Generated by Django 4.2.6 on 2023-10-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PI_WEB', '0005_groups_permissions'),
        ('PI_WEB', '0006_reserva_status'),
    ]

    operations = [
    ]
